controllers:
    host: 'exosymfony.fr'
    resource: ../../src/Controller/
    type: annotation

api_controllers:
    host: 'api.exosymfony.fr'
    resource: ../../src/ApiController/
    type: annotation
